package hu.ash.contractregistry.model;

// @formatter:off

public enum Role {
    ADMIN,
    USER,
    
    GUARANTEE_NATURE_VIEW,
    GUARANTEE_TYPE_VIEW,
    DOCUMENT_TYPE_VIEW,
    CONTACT_TYPE_VIEW,
    COST_CENTER_VIEW,
    PENALTY_TYPE_VIEW,
    DELIVERABLE_PRODUCT_VIEW,
    REGISTER_NUMBER_TYPE_VIEW,
    CURRENCY_VIEW,
    TEMPLATE_TYPE_VIEW,
    CONTRACT_LINK_TYPE_VIEW,
    CONTRACT_TYPE_VIEW,
    DOCUMENT_TEMPLATE_VIEW,
    CONTRACT_CLOSING_REASON_VIEW,
    PAYMENT_TYPE_VIEW,
    
    PARTNER_VIEW,
    PARTNER_EDIT,
    PARTNER_DELETE,
    
    CONTRACT_VIEW,
    CONTRACT_EDIT,
    CONTRACT_DELETE,
    
    CONTRACT_FINANCIAL_DATA_VIEW,
    CONTRACT_FINANCIAL_DATA_EDIT,
    CONTRACT_DOCUMENTS_VIEW,
    CONTRACT_DOCUMENTS_EDIT,
    CONTRACT_CONNECTED_CONTRACTS_VIEW,
    CONTRACT_CONNECTED_CONTRACTS_EDIT,
    CONTRACT_CONTACT_VIEW,
    CONTRACT_CONTACT_CONTRACTS_EDIT,
    CONTRACT_NOTES_VIEW,
    CONTRACT_NOTES_CONTRACTS_EDIT,

    TASK_ALL_VIEW,
    PARTNER_CONTRACT_CONNECTION_QUERY,
    ;
}

//@formatter:on
